[package]
name = "hidapi"
version = "0.5.0"
authors = [
    "Roland Ruckerbauer <roland.rucky@gmail.com>",
    "Osspial <osspial@gmail.com>",
    "Artyom Pavlov <newpavlov@gmail.com>",
	"mberndt123"
]
repository = "https://github.com/Osspial/hidapi-rs"
description = "Rust-y wrapper around hidapi"
license = "MIT"
keywords = ["hid", "api", "usb","binding", "wrapper"]
build = "build.rs"
links = "hidapi"
documentation = "https://docs.rs/hidapi"

[features]
default = ["linux-rust-hidraw"]
linux-static-libusb = ["libc"]
linux-static-hidraw = ["libc"]
linux-shared-libusb = ["libc"]
linux-shared-hidraw = ["libc"]
linux-rust-hidraw = ["libudev", "nix"]

[dependencies]
libc = { version = "0.2.33", optional = true }
failure = "0.1.2"
failure_derive = "0.1.2"
nix = { version = "0.11.0", optional = true }
libudev = { version = "0.2.0", optional = true }

[build-dependencies]
cc = "1.0.3"
pkg-config = "0.3.9"
