[package]
name = "hidapi"
version = "0.5.0"
authors = [
    "Roland Ruckerbauer <roland.rucky@gmail.com>",
    "Osspial <osspial@gmail.com>",
    "Artyom Pavlov <newpavlov@gmail.com>",
	"mberndt123"
]
repository = "https://github.com/Osspial/hidapi-rs"
description = "Rust-y wrapper around hidapi"
license = "MIT"
keywords = ["hid", "api", "usb","binding", "wrapper"]
build = "build.rs"
links = "hidapi"
documentation = "https://docs.rs/hidapi"

[features]
default = ["linux-rust-hidraw"]
linux-static-libusb = []
linux-static-hidraw = []
linux-shared-libusb = []
linux-shared-hidraw = []
linux-rust-hidraw = ["udev"]

[dependencies]
libc = "0.2.33"
failure = "0.1.2"
failure_derive = "0.1.2"
udev = { version = "0.2.0", optional = true }

[build-dependencies]
cc = "1.0.3"
pkg-config = "0.3.9"
