[package]
name = "hidapi"
version = "0.0.1"
authors = ["Roland Ruckerbauer <roland.rucky@gmail.com>", "Osspial <osspial@gmail.com"]
repository = "https://github.com/Osspial/hidapi-rs"
description = "In development hidapi binding for rust"
license = "LGPL-3.0+"
keywords = ["hid", "api", "binding"]
build = "build.rs"
links = "hidapi"

[dependencies]
libc = "0.1.8"

[build-dependencies]
gcc = "0.3"
pkg-config = "0.3.5"
